add Search Engine + translations into german
pierreozoux/ihavesomethingtohi.de pull request #45
Opened 2018-02-24 22:37 UTC by frju365

fixes #36

2018-02-24 23:25 UTC, pierreozoux requested changes

2018-02-24 23:25 UTC, pierreozoux commented on app/_en_tools/search_engine.md
> +- [Searx](https://searx.me/) : Sie können diese Software auf Ihren Server haben. [Quellcode](https://github.com/asciimoo/searx)
german description

2018-02-24 23:25 UTC, pierreozoux commented
Thanks for all the hard work!

2018-02-25 00:27 UTC, frju365 commented
Corrigé.

2018-02-25 00:32 UTC, frju365 commented
Ce n'est pas très difficile. Je pense qu'en traduisant et en développant une certaine connaissance, on peut réussir à convaincre beaucoup de monde (du moins il s'agit au moins d'essayer). C'est une "croisade" qui est menée par toutes les communautés de logiciels libres ou qui souhaitent faire avancer la roue de la liberté.

2018-02-25 00:47 UTC, frju365 commented
Prochaine étape : les distributions linux.

2018-02-25 06:50 UTC, pierreozoux approved these changes

2018-02-25 09:17 UTC, merged